// <auto-generated />
using System;
using Cribbage.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cribbage.PL.Migrations
{
    [DbContext(typeof(CribbageEntities))]
    [Migration("20240202153340_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cribbage.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Player_1_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player_1_Score")
                        .HasColumnType("int");

                    b.Property<Guid>("Player_2_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player_2_Score")
                        .HasColumnType("int");

                    b.Property<Guid>("Winner")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3737424-0c85-4516-9022-341371195965"),
                            Date = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("fdff717a-9025-4a3f-9021-d7ebf420ee29"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("242a8880-a784-4caa-a914-599418ba0dee"),
                            Player_2_Score = 70,
                            Winner = new Guid("fdff717a-9025-4a3f-9021-d7ebf420ee29")
                        },
                        new
                        {
                            Id = new Guid("21fb24d3-cdb5-47f1-aa48-a8ff56d4d7ce"),
                            Date = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("242a8880-a784-4caa-a914-599418ba0dee"),
                            Player_1_Score = 90,
                            Player_2_Id = new Guid("dee8d805-06d2-4f58-887d-033db2d3f097"),
                            Player_2_Score = 121,
                            Winner = new Guid("dee8d805-06d2-4f58-887d-033db2d3f097")
                        },
                        new
                        {
                            Id = new Guid("5ed24903-f406-496e-85a2-c2d9c2bdd353"),
                            Date = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("242a8880-a784-4caa-a914-599418ba0dee"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("fdff717a-9025-4a3f-9021-d7ebf420ee29"),
                            Player_2_Score = 85,
                            Winner = new Guid("242a8880-a784-4caa-a914-599418ba0dee")
                        },
                        new
                        {
                            Id = new Guid("001ac473-be2a-4909-ad85-3b57c73f39ff"),
                            Date = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("2cf37fd1-6663-4b6d-ba9e-4f320bcd0736"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("242a8880-a784-4caa-a914-599418ba0dee"),
                            Player_2_Score = 50,
                            Winner = new Guid("2cf37fd1-6663-4b6d-ba9e-4f320bcd0736")
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPtsPerGame")
                        .HasColumnType("float");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinStreak")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cf37fd1-6663-4b6d-ba9e-4f320bcd0736"),
                            AvgPtsPerGame = 121.0,
                            DisplayName = "CardMaster",
                            Email = "cribbage@game.com",
                            FirstName = "Joe",
                            GamesStarted = 1,
                            LastName = "Smith",
                            Losses = 0,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("fdff717a-9025-4a3f-9021-d7ebf420ee29"),
                            AvgPtsPerGame = 103.0,
                            DisplayName = "CribbageBox",
                            Email = "fun@yahoo.com",
                            FirstName = "Peter",
                            GamesStarted = 2,
                            LastName = "Parker",
                            Losses = 1,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("242a8880-a784-4caa-a914-599418ba0dee"),
                            AvgPtsPerGame = 82.75,
                            DisplayName = "GamesRCool",
                            Email = "cards@me.com",
                            FirstName = "Kelly",
                            GamesStarted = 4,
                            LastName = "Bot",
                            Losses = 3,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("dee8d805-06d2-4f58-887d-033db2d3f097"),
                            AvgPtsPerGame = 121.0,
                            DisplayName = "Testing",
                            Email = "tester@gmail.com",
                            FirstName = "Test",
                            GamesStarted = 1,
                            LastName = "Tester",
                            Losses = 0,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -99,
                            GameId = new Guid("d3737424-0c85-4516-9022-341371195965"),
                            UserId = new Guid("fdff717a-9025-4a3f-9021-d7ebf420ee29")
                        },
                        new
                        {
                            Id = -98,
                            GameId = new Guid("21fb24d3-cdb5-47f1-aa48-a8ff56d4d7ce"),
                            UserId = new Guid("dee8d805-06d2-4f58-887d-033db2d3f097")
                        },
                        new
                        {
                            Id = -97,
                            GameId = new Guid("5ed24903-f406-496e-85a2-c2d9c2bdd353"),
                            UserId = new Guid("242a8880-a784-4caa-a914-599418ba0dee")
                        },
                        new
                        {
                            Id = -96,
                            GameId = new Guid("001ac473-be2a-4909-ad85-3b57c73f39ff"),
                            UserId = new Guid("2cf37fd1-6663-4b6d-ba9e-4f320bcd0736")
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Cribbage.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Cribbage.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
