// <auto-generated />
using System;
using Cribbage.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cribbage.PL.Migrations
{
    [DbContext(typeof(CribbageEntities))]
    [Migration("20240202164857_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cribbage.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Player_1_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player_1_Score")
                        .HasColumnType("int");

                    b.Property<Guid>("Player_2_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Player_2_Score")
                        .HasColumnType("int");

                    b.Property<Guid>("Winner")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41ebb35f-6aac-4777-b9f2-7a957174cc82"),
                            Date = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("b17eef8c-98f6-40d4-892a-e6eaf69fb981"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759"),
                            Player_2_Score = 70,
                            Winner = new Guid("b17eef8c-98f6-40d4-892a-e6eaf69fb981")
                        },
                        new
                        {
                            Id = new Guid("eb62f38d-4e79-4616-9bae-f4a061206009"),
                            Date = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759"),
                            Player_1_Score = 90,
                            Player_2_Id = new Guid("4f80cec3-f8da-4264-b048-644b5ad75916"),
                            Player_2_Score = 121,
                            Winner = new Guid("4f80cec3-f8da-4264-b048-644b5ad75916")
                        },
                        new
                        {
                            Id = new Guid("1e3bf796-4f18-49c5-8378-e185d41b8990"),
                            Date = new DateTime(2023, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("b17eef8c-98f6-40d4-892a-e6eaf69fb981"),
                            Player_2_Score = 85,
                            Winner = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759")
                        },
                        new
                        {
                            Id = new Guid("4667fe20-59da-4ad8-8c7f-075b45fdf640"),
                            Date = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player_1_Id = new Guid("d58ab8af-84fb-417f-af19-6a2d6ae36619"),
                            Player_1_Score = 121,
                            Player_2_Id = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759"),
                            Player_2_Score = 50,
                            Winner = new Guid("d58ab8af-84fb-417f-af19-6a2d6ae36619")
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPtsPerGame")
                        .HasColumnType("float");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinStreak")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d58ab8af-84fb-417f-af19-6a2d6ae36619"),
                            AvgPtsPerGame = 121.0,
                            DisplayName = "CardMaster",
                            Email = "cribbage@game.com",
                            FirstName = "Joe",
                            GamesStarted = 1,
                            LastName = "Smith",
                            Losses = 0,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("b17eef8c-98f6-40d4-892a-e6eaf69fb981"),
                            AvgPtsPerGame = 103.0,
                            DisplayName = "CribbageBox",
                            Email = "fun@yahoo.com",
                            FirstName = "Peter",
                            GamesStarted = 2,
                            LastName = "Parker",
                            Losses = 1,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759"),
                            AvgPtsPerGame = 82.75,
                            DisplayName = "GamesRCool",
                            Email = "cards@me.com",
                            FirstName = "Kelly",
                            GamesStarted = 4,
                            LastName = "Bot",
                            Losses = 3,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("4f80cec3-f8da-4264-b048-644b5ad75916"),
                            AvgPtsPerGame = 121.0,
                            DisplayName = "Testing",
                            Email = "tester@gmail.com",
                            FirstName = "Test",
                            GamesStarted = 1,
                            LastName = "Tester",
                            Losses = 0,
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            WinStreak = 1,
                            Wins = 1
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -99,
                            GameId = new Guid("41ebb35f-6aac-4777-b9f2-7a957174cc82"),
                            UserId = new Guid("b17eef8c-98f6-40d4-892a-e6eaf69fb981")
                        },
                        new
                        {
                            Id = -98,
                            GameId = new Guid("eb62f38d-4e79-4616-9bae-f4a061206009"),
                            UserId = new Guid("4f80cec3-f8da-4264-b048-644b5ad75916")
                        },
                        new
                        {
                            Id = -97,
                            GameId = new Guid("1e3bf796-4f18-49c5-8378-e185d41b8990"),
                            UserId = new Guid("1f9c4ba8-3fd3-47e0-994b-d770561f6759")
                        },
                        new
                        {
                            Id = -96,
                            GameId = new Guid("4667fe20-59da-4ad8-8c7f-075b45fdf640"),
                            UserId = new Guid("d58ab8af-84fb-417f-af19-6a2d6ae36619")
                        });
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Cribbage.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Cribbage.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Cribbage.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
